logo_monkey = []
logo_monkey.append("                __,__                   ")
logo_monkey.append("       .--.  .-"     "-.  .--.          ")
logo_monkey.append("      / .. \/  .-. .-.  \/ .. \         ")
logo_monkey.append("     | |  '|  /   Y   \  |'  | |        ")
logo_monkey.append("     | \   \  \ 0 | 0 /  /   / |        ")
logo_monkey.append("       \ '- ,\.-\"`` ``\"-./, -' /        ")
logo_monkey.append("       `'-' /_   ^ ^   _\ '-'`          ")
logo_monkey.append("       .--'|  \._ _ _./  |'--.          ")
logo_monkey.append("     /`    \   \.-.  /   /    `\        ")
logo_monkey.append("    /       '._/  |-' _.'       \       ")
logo_monkey.append("   /          ;  /--~'   |       \      ")
logo_monkey.append("  /        .'\|.-\--.     \       \     ")
logo_monkey.append(" /   .'-. /.-.;\  |\|'~'-.|\       \    ")
logo_monkey.append(" \       `-./`|_\_/ `     `\'.      \   ")
logo_monkey.append("  '.      ;     ___)        '.`;    /   ")
logo_monkey.append("    '-.,_ ;     ___)          \/   /    ")
logo_monkey.append("     \   ``'------'\       \   `  /     ")
logo_monkey.append("      '.    \       '.      |   ;/_     ")
logo_monkey.append("    ___>     '.       \_ _ _/   ,  '--. ")
logo_monkey.append("  .'   '.   .-~~~~~-. /     |--'`~~-.  |")
logo_monkey.append(" // / .---'/  .-~~-._/ / / /---..__.'  /")
logo_monkey.append("((_(_/    /  /      (_(_(_(---.__    .' ")
logo_monkey.append("          | |     _              `~~`   ")
logo_monkey.append("          | |     \'.                   ")
logo_monkey.append("           \ '....' |                   ")
logo_monkey.append("            '.,___.'                    ")
